# -*- coding: utf-8 -*-
"""Flashcard verificabili — parte B: misurazione, infrastruttura, analisi di business."""

FLASHCARD_B = [
# ================================================================= KPI E MISURAZIONE
dict(id="KPI-01", tema="kpi", domanda="Come definisce Hubbard la «misurazione»?",
 risposta="Una riduzione quantificata dell'incertezza basata su osservazione. Non serve la precisione assoluta: se un'osservazione riduce l'incertezza rispetto a prima, è una misurazione valida.",
 fonte="Hubbard, How to Measure Anything, 3ª ed.", riferimento="Cap. 3 — The illusion of intangibles"),
dict(id="KPI-02", tema="kpi", domanda="Che cos'è la «catena di chiarificazione» di Hubbard?",
 risposta="Se conta, si nota; se si nota, si manifesta in qualche quantità osservabile; se si manifesta in una quantità, si può misurare. Serve a smontare l'obiezione «questo non è misurabile».",
 fonte="Hubbard, How to Measure Anything, 3ª ed.", riferimento="Cap. 3 — Clarification chain"),
dict(id="KPI-03", tema="kpi", domanda="Che cos'è la «regola del cinque»?",
 risposta="Con un campione casuale di soli cinque elementi, c'è circa il 93,75% di probabilità che la mediana della popolazione cada tra il valore minimo e il massimo osservati. Mostra quanta incertezza si riduce con pochissimi dati.",
 fonte="Hubbard, How to Measure Anything, 3ª ed.", riferimento="Cap. 9 — Rule of five"),
dict(id="KPI-04", tema="kpi", domanda="Che cos'è il valore atteso dell'informazione e come cambia le priorità di misurazione?",
 risposta="È il valore economico della riduzione di incertezza rispetto a una decisione. Ribalta le priorità: si misura ciò che ha alto valore informativo e alta incertezza, non ciò che è facile da misurare. Le variabili più misurate sono spesso quelle che contano meno.",
 fonte="Hubbard, How to Measure Anything, 3ª ed.", riferimento="Cap. 7 — Value of information"),
dict(id="KPI-05", tema="kpi", domanda="Che cos'è la calibrazione della stima e perché è addestrabile?",
 risposta="È la capacità di esprimere intervalli di confidenza che contengono il valore reale con la frequenza dichiarata. Le persone non addestrate sono sistematicamente sovra-sicure; l'addestramento con feedback ripetuto porta la maggioranza a una calibrazione affidabile in poche ore.",
 fonte="Hubbard, How to Measure Anything, 3ª ed.", riferimento="Cap. 5 — Calibrated estimates"),
dict(id="KPI-06", tema="kpi", domanda="Qual è la differenza tra indicatore leading e lagging?",
 risposta="Il lagging misura il risultato a valle e conferma ciò che è già accaduto; il leading misura un fattore a monte che anticipa il risultato e su cui si può ancora intervenire. Un cruscotto di soli lagging non permette di correggere la rotta.",
 fonte="Kaplan & Norton, The Balanced Scorecard", riferimento="Outcome measures and performance drivers"),
dict(id="KPI-07", tema="kpi", domanda="Quali sono le quattro prospettive della Balanced Scorecard?",
 risposta="Finanziaria, cliente, processi interni, apprendimento e crescita. L'idea centrale è che le quattro siano legate da relazioni causali esplicite, non elencate in parallelo.",
 fonte="Kaplan & Norton, The Balanced Scorecard", riferimento="Cap. 1"),
dict(id="KPI-08", tema="kpi", domanda="Enuncia la legge di Goodhart e la sua rilevanza per i KPI.",
 risposta="Quando una misura diventa un obiettivo, cessa di essere una buona misura. Ogni indicatore usato per valutare le persone genera incentivi a ottimizzare l'indicatore invece del risultato che intendeva rappresentare.",
 fonte="Goodhart (1975); formulazione di Strathern (1997)", riferimento="Improving ratings: audit in the British University system"),
dict(id="KPI-09", tema="kpi", domanda="Quali sono le quattro metriche DORA?",
 risposta="Frequenza di rilascio, lead time per una modifica, tasso di fallimento delle modifiche, tempo di ripristino del servizio. Le prime due misurano la velocità, le altre due la stabilità — e i dati mostrano che non sono in trade-off.",
 fonte="Forsgren, Humble & Kim, Accelerate", riferimento="Cap. 2 — Measuring performance"),
dict(id="KPI-10", tema="kpi", domanda="Qual è la differenza tra SLI, SLO e SLA?",
 risposta="L'SLI è l'indicatore misurato (per esempio la percentuale di richieste andate a buon fine); l'SLO è l'obiettivo interno su quell'indicatore; l'SLA è l'impegno contrattuale verso l'esterno, con conseguenze in caso di violazione. L'SLO dovrebbe sempre essere più stringente dell'SLA.",
 fonte="Google SRE Book", riferimento="Cap. 4 — Service level objectives"),
dict(id="KPI-11", tema="kpi", domanda="Che cos'è l'error budget e a che cosa serve?",
 risposta="È la quota di inaffidabilità tollerata dall'SLO — il complemento a 100% dell'obiettivo. Trasforma il conflitto tra sviluppo e affidabilità in una regola oggettiva: finché il budget è capiente si può rilasciare, quando è esaurito la priorità passa alla stabilità.",
 fonte="Google SRE Book", riferimento="Cap. 3 — Embracing risk"),
dict(id="KPI-12", tema="kpi", domanda="Che cos'è un albero delle metriche?",
 risposta="Una scomposizione gerarchica di una metrica di vertice in fattori moltiplicativi o additivi fino a variabili operative su cui qualcuno può agire. Rende esplicito il legame tra il KPI di direzione e il lavoro quotidiano.",
 fonte="Prassi di analytics engineering; cfr. dbt Labs — Semantic layer", riferimento="Metric trees / metric decomposition"),
dict(id="KPI-13", tema="kpi", domanda="Che cos'è un layer semantico e quale problema di governance risolve?",
 risposta="È la definizione centralizzata e versionata delle metriche, disaccoppiata dagli strumenti di visualizzazione. Risolve la proliferazione di definizioni divergenti della stessa metrica in dashboard diverse.",
 fonte="dbt Labs — documentazione ufficiale", riferimento="Semantic layer / MetricFlow"),
dict(id="KPI-14", tema="kpi", domanda="Quali sono i limiti del criterio SMART per gli indicatori?",
 risposta="Premia gli obiettivi facilmente quantificabili e a breve termine, penalizzando ciò che è rilevante ma difficile da misurare; non dice nulla sulla validità del costrutto, cioè se l'indicatore misuri davvero ciò che dichiara.",
 fonte="Critica consolidata in letteratura MEL; cfr. ALNAP", riferimento="Evaluation of humanitarian action guide"),
dict(id="KPI-15", tema="kpi", domanda="Che cos'è la validità di costrutto applicata a un indicatore?",
 risposta="Il grado in cui l'indicatore misura effettivamente il concetto che intende rappresentare. Un indicatore può essere preciso, affidabile e tempestivo e nondimeno misurare la cosa sbagliata.",
 fonte="Metodologia della ricerca sociale; cfr. OECD-DAC", riferimento="Criteri di valutazione — rilevanza e validità"),
dict(id="KPI-16", tema="kpi", domanda="Quali sono i sei criteri di valutazione OECD-DAC?",
 risposta="Rilevanza, coerenza, efficacia, efficienza, impatto e sostenibilità. La coerenza è stata aggiunta nella revisione del 2019.",
 fonte="OECD-DAC", riferimento="Evaluation criteria, revisione 2019"),
dict(id="KPI-17", tema="kpi", domanda="Che cos'è il Core Humanitarian Standard e quanti impegni prevede?",
 risposta="Uno standard che definisce ciò che le comunità colpite possono attendersi dalle organizzazioni umanitarie, articolato in nove impegni con criteri di qualità associati, tra cui accesso a meccanismi di reclamo sicuri e accessibili.",
 fonte="Core Humanitarian Standard on Quality and Accountability", riferimento="I nove impegni"),
dict(id="KPI-18", tema="kpi", domanda="Che differenza c'è tra output, outcome e impatto in una teoria del cambiamento?",
 risposta="L'output è il prodotto diretto dell'attività e sotto il controllo dell'organizzazione; l'outcome è il cambiamento a breve-medio termine nei beneficiari, influenzato ma non controllato; l'impatto è l'effetto di lungo periodo, a cui si può solo contribuire.",
 fonte="OECD-DAC / quadro logico", riferimento="Results chain"),
dict(id="KPI-19", tema="kpi", domanda="Perché un indicatore di processo non può sostituire un indicatore di risultato?",
 risposta="Perché misura l'esecuzione dell'attività, non il cambiamento prodotto. Un programma può registrare il 100% delle attività pianificate e non produrre alcun effetto: senza un indicatore di risultato la differenza resta invisibile.",
 fonte="ALNAP", riferimento="Evaluation of humanitarian action guide"),
dict(id="KPI-20", tema="kpi", domanda="Che cos'è il costo per risultato e perché è un indicatore di efficienza fragile?",
 risposta="È il rapporto tra costo totale e unità di risultato prodotta. È fragile perché dipende fortemente dal contesto operativo — accessibilità, sicurezza, scala — e confrontarlo tra programmi diversi senza normalizzazione produce conclusioni errate.",
 fonte="OECD-DAC — criterio di efficienza", riferimento="Cost-efficiency analysis"),

# ================================================================= RETI E HARDWARE
dict(id="NET-01", tema="hardware", domanda="Quali sono i sette livelli del modello OSI?",
 risposta="Fisico, collegamento dati, rete, trasporto, sessione, presentazione, applicazione.",
 fonte="ISO/IEC 7498-1", riferimento="Modello di riferimento OSI"),
dict(id="NET-02", tema="hardware", domanda="Qual è la differenza operativa tra TCP e UDP?",
 risposta="TCP è orientato alla connessione, garantisce consegna ordinata e affidabile con ritrasmissione e controllo di flusso; UDP è senza connessione, senza garanzie di consegna né di ordine, ma con latenza e overhead minori. Voce e video preferiscono UDP, i trasferimenti di dati TCP.",
 fonte="RFC 793 (TCP) e RFC 768 (UDP)", riferimento="Specifiche di protocollo"),
dict(id="NET-03", tema="hardware", domanda="Che differenza c'è tra latenza, larghezza di banda e throughput?",
 risposta="La latenza è il tempo di attraversamento di un pacchetto; la larghezza di banda è la capacità teorica massima del collegamento; il throughput è il dato effettivamente trasferito nell'unità di tempo. Una banda ampia con latenza alta resta inadatta alle applicazioni interattive.",
 fonte="Grigorik, High Performance Browser Networking", riferimento="Cap. 1 — Primer on latency and bandwidth"),
dict(id="NET-04", tema="hardware", domanda="Che cos'è il bandwidth-delay product e perché conta su collegamenti satellitari?",
 risposta="È il prodotto tra capacità del collegamento e tempo di andata e ritorno: rappresenta la quantità di dati «in volo». Su un collegamento a latenza alta occorrono finestre TCP ampie per saturare la banda; altrimenti il collegamento resta sottoutilizzato anche se nominalmente veloce.",
 fonte="Grigorik, High Performance Browser Networking", riferimento="Cap. 2 — Building blocks of TCP"),
dict(id="NET-05", tema="hardware", domanda="Quali sono gli ordini di grandezza della latenza di andata e ritorno per satellite geostazionario e per costellazione in orbita bassa?",
 risposta="Un satellite geostazionario, a circa 35.786 km, comporta un tempo di andata e ritorno tipicamente intorno ai 500-600 millisecondi; le costellazioni in orbita terrestre bassa, a poche centinaia di chilometri, scendono a poche decine di millisecondi.",
 fonte="Parametri orbitali standard; documentazione operatori VSAT", riferimento="Verificare i valori reali del fornitore contrattualizzato"),
dict(id="NET-06", tema="hardware", domanda="Quali sono gli intervalli di indirizzi IPv4 privati?",
 risposta="10.0.0.0/8, 172.16.0.0/12 e 192.168.0.0/16.",
 fonte="RFC 1918", riferimento="Address allocation for private internets"),
dict(id="NET-07", tema="hardware", domanda="Quanti host utilizzabili contiene una sottorete /24 e perché due indirizzi non sono assegnabili?",
 risposta="254. Su 256 indirizzi totali, il primo è l'indirizzo di rete e l'ultimo è l'indirizzo di broadcast, entrambi non assegnabili a un host.",
 fonte="RFC 950 / RFC 4632 (CIDR)", riferimento="Subnetting"),
dict(id="NET-08", tema="hardware", domanda="Che cosa fanno rispettivamente DNS, DHCP e NAT?",
 risposta="Il DNS risolve i nomi in indirizzi IP; il DHCP assegna dinamicamente indirizzi e parametri di rete ai client; il NAT traduce indirizzi privati in uno o più indirizzi pubblici, consentendo a molti dispositivi di condividere un'uscita.",
 fonte="RFC 1035, RFC 2131, RFC 3022", riferimento="Specifiche di protocollo"),
dict(id="NET-09", tema="hardware", domanda="Che cos'è la MTU e che effetto ha una MTU errata su una VPN?",
 risposta="È la dimensione massima del pacchetto trasmissibile senza frammentazione. Una VPN aggiunge intestazioni di incapsulamento: se la MTU non viene ridotta di conseguenza, i pacchetti vengono frammentati o scartati, con sintomi tipici come connessioni che si aprono ma trasferimenti che si bloccano.",
 fonte="RFC 1191 — Path MTU Discovery", riferimento="Frammentazione e PMTUD"),
dict(id="NET-10", tema="hardware", domanda="Qual è la differenza tra IOPS e throughput in uno storage?",
 risposta="Gli IOPS misurano il numero di operazioni di input/output al secondo e contano per carichi con accessi piccoli e casuali, come i database; il throughput misura i megabyte al secondo e conta per letture e scritture sequenziali di grandi file.",
 fonte="Documentazione tecnica di storage; cfr. AWS EBS docs", riferimento="Volume performance characteristics"),
dict(id="NET-11", tema="hardware", domanda="Che cosa distingue RAID 1, RAID 5 e RAID 10?",
 risposta="RAID 1 specchia i dati su due dischi e tollera la perdita di uno; RAID 5 distribuisce dati e parità su almeno tre dischi, tollera un guasto e ha una ricostruzione lenta e rischiosa; RAID 10 combina mirroring e striping, offrendo prestazioni e tolleranza migliori a costo di metà della capacità.",
 fonte="Patterson, Gibson & Katz (1988) — tassonomia RAID", riferimento="A case for redundant arrays of inexpensive disks"),
dict(id="NET-12", tema="hardware", domanda="Perché il RAID non è un backup?",
 risposta="Perché protegge dal guasto hardware di un disco, non dalla cancellazione accidentale, dalla corruzione logica, dal ransomware o dalla distruzione fisica del sito. Tutti questi eventi si replicano istantaneamente su tutti i dischi dell'array.",
 fonte="Principio consolidato di continuità operativa; cfr. NIST SP 800-34", riferimento="Contingency planning guide"),
dict(id="NET-13", tema="hardware", domanda="Che cos'è la regola di backup 3-2-1?",
 risposta="Tre copie dei dati, su due supporti differenti, di cui una conservata fuori sede. Le varianti recenti aggiungono una copia immutabile o offline e la verifica periodica del ripristino.",
 fonte="Prassi consolidata di disaster recovery; cfr. NIST SP 800-34", riferimento="Backup strategy"),
dict(id="NET-14", tema="hardware", domanda="Qual è la differenza tra RTO e RPO?",
 risposta="L'RTO è il tempo massimo tollerabile per ripristinare il servizio dopo un'interruzione; l'RPO è la quantità massima di dati che ci si può permettere di perdere, espressa come finestra temporale. L'RTO dimensiona la procedura di ripristino, l'RPO la frequenza dei backup.",
 fonte="NIST SP 800-34 Rev. 1", riferimento="Contingency planning guide for federal information systems"),
dict(id="NET-15", tema="hardware", domanda="Che cos'è la memoria ECC e quando è necessaria?",
 risposta="Memoria con codice di correzione d'errore, in grado di rilevare e correggere errori su singolo bit causati da disturbi elettrici o radiazione. È raccomandata per server e sistemi che conservano dati critici, dove una corruzione silenziosa è inaccettabile.",
 fonte="Documentazione tecnica dei produttori di memoria", riferimento="ECC vs non-ECC DRAM"),
dict(id="NET-16", tema="hardware", domanda="Come si dimensiona un gruppo di continuità per un carico dato?",
 risposta="Si somma la potenza attiva in watt dei carichi, si applica un margine di sicurezza, si verifica che non si superi né la potenza in VA né quella in watt dell'apparato, e si calcola l'autonomia dividendo l'energia disponibile in wattora per il carico effettivo, tenendo conto del rendimento.",
 fonte="Documentazione tecnica UPS; cfr. IEC 62040", riferimento="Uninterruptible power systems"),
dict(id="NET-17", tema="hardware", domanda="Che cosa distingue un'architettura ARM da una x86 e perché importa nella scelta dei dispositivi di campo?",
 risposta="ARM adotta un set di istruzioni ridotto con efficienza energetica superiore, x86 un set complesso con prestazioni di picco storicamente maggiori. Su campo, dove l'energia è vincolo primario e la dissipazione passiva è preferibile, l'efficienza per watt di ARM diventa il criterio dominante.",
 fonte="Letteratura di architettura dei calcolatori; cfr. Hennessy & Patterson", riferimento="Computer Architecture: A Quantitative Approach"),
dict(id="NET-18", tema="hardware", domanda="Quando conviene inferire un modello di IA in locale anziché tramite API?",
 risposta="Quando i dati non possono lasciare il perimetro per vincoli normativi o di protezione, quando la connettività è assente o instabile, o quando il volume costante rende il costo per chiamata superiore all'ammortamento dell'hardware. L'API resta preferibile per volumi variabili e bassa intensità.",
 fonte="Huyen, AI Engineering", riferimento="Cap. su inference optimization e cost"),
dict(id="NET-19", tema="hardware", domanda="Che cos'è la latenza del primo token e perché è distinta dal throughput di generazione?",
 risposta="È il tempo che intercorre prima che il modello produca il primo token di risposta e determina la percezione di reattività; il throughput di generazione misura i token al secondo successivi e determina il tempo totale. Un sistema può avere throughput elevato e risultare comunque lento alla percezione.",
 fonte="Huyen, AI Engineering", riferimento="Metriche di latenza dell'inferenza"),
dict(id="NET-20", tema="hardware", domanda="Che cos'è il MDM e perché è centrale nella gestione di una flotta di dispositivi sul campo?",
 risposta="La gestione centralizzata dei dispositivi mobili, che consente configurazione, distribuzione delle applicazioni, applicazione delle politiche di sicurezza, cifratura obbligatoria e cancellazione remota in caso di smarrimento. Senza MDM, la perdita di un tablet equivale a una potenziale violazione di dati.",
 fonte="NIST SP 1800-4 / SP 800-124", riferimento="Mobile device security"),
dict(id="NET-21", tema="hardware", domanda="Che cos'è la cifratura a riposo e in transito, e perché servono entrambe?",
 risposta="A riposo protegge i dati memorizzati su disco da accesso fisico o furto del dispositivo; in transito protegge i dati mentre viaggiano in rete da intercettazione. Sono controlli su minacce diverse: nessuna delle due sostituisce l'altra.",
 fonte="ISO/IEC 27002 / NIST SP 800-175B", riferimento="Controlli crittografici"),
dict(id="NET-22", tema="hardware", domanda="Quali sono le cinque funzioni del NIST Cybersecurity Framework 2.0?",
 risposta="Govern, Identify, Protect, Detect, Respond, Recover. La funzione Govern è stata introdotta nella versione 2.0 e attraversa tutte le altre.",
 fonte="NIST CSF 2.0", riferimento="Core functions"),

# ================================================================= BUSINESS ANALYSIS
dict(id="BAB-01", tema="business_analysis", domanda="Quali sono le sei aree di conoscenza del BABOK v3?",
 risposta="Pianificazione e monitoraggio della business analysis; elicitazione e collaborazione; gestione del ciclo di vita dei requisiti; analisi strategica; analisi dei requisiti e definizione del design; valutazione della soluzione.",
 fonte="IIBA, BABOK Guide v3", riferimento="Knowledge areas"),
dict(id="BAB-02", tema="business_analysis", domanda="Come classifica il BABOK i requisiti?",
 risposta="Requisiti di business, requisiti degli stakeholder, requisiti di soluzione — suddivisi in funzionali e non funzionali — e requisiti di transizione, che valgono solo durante il passaggio dallo stato attuale a quello futuro.",
 fonte="IIBA, BABOK Guide v3", riferimento="Requirements classification schema"),
dict(id="BAB-03", tema="business_analysis", domanda="Che cos'è l'analisi as-is / to-be e a cosa serve il gap?",
 risposta="La descrizione dello stato attuale e dello stato desiderato di un processo; il divario tra i due definisce l'ambito del cambiamento e giustifica le iniziative. Senza as-is documentato, il to-be è un'aspirazione non verificabile.",
 fonte="IIBA, BABOK Guide v3", riferimento="Strategy analysis — current and future state"),
dict(id="BAB-04", tema="business_analysis", domanda="Quali sono le quattro categorie di elementi BPMN?",
 risposta="Oggetti di flusso (eventi, attività, gateway); oggetti di connessione (flussi di sequenza, flussi di messaggio, associazioni); corsie (pool e lane); artefatti (oggetti dati, gruppi, annotazioni).",
 fonte="OMG, BPMN 2.0", riferimento="Specifica — elementi di base"),
dict(id="BAB-05", tema="business_analysis", domanda="Che differenza c'è tra gateway esclusivo, parallelo e inclusivo in BPMN?",
 risposta="L'esclusivo attiva esattamente un percorso in base a una condizione; il parallelo attiva tutti i percorsi contemporaneamente senza valutare condizioni; l'inclusivo attiva tutti i percorsi le cui condizioni risultano vere, da uno a tutti.",
 fonte="OMG, BPMN 2.0", riferimento="Gateway types"),
dict(id="BAB-06", tema="business_analysis", domanda="Qual è la differenza tra pool e lane in BPMN?",
 risposta="Il pool rappresenta un partecipante o un'entità organizzativa autonoma: tra pool diversi si comunica solo con flussi di messaggio. La lane è una suddivisione interna al pool, tipicamente un ruolo, e al suo interno il flusso di sequenza è consentito.",
 fonte="OMG, BPMN 2.0", riferimento="Swimlanes"),
dict(id="BAB-07", tema="business_analysis", domanda="Che cos'è una matrice RACI?",
 risposta="Uno strumento di assegnazione delle responsabilità che per ogni attività distingue chi esegue (Responsible), chi risponde del risultato (Accountable), chi viene consultato (Consulted) e chi viene informato (Informed). Regola fondamentale: un solo Accountable per attività.",
 fonte="IIBA, BABOK Guide v3", riferimento="Stakeholder analysis — RACI matrix"),
dict(id="BAB-08", tema="business_analysis", domanda="Che cos'è la prioritizzazione MoSCoW?",
 risposta="Una classificazione dei requisiti in Must have, Should have, Could have e Won't have (per questa volta). Funziona solo se la quota di Must è limitata: se tutto è indispensabile, il metodo non fornisce alcuna informazione.",
 fonte="IIBA, BABOK Guide v3", riferimento="Prioritization techniques"),
dict(id="BAB-09", tema="business_analysis", domanda="Che cos'è un criterio di accettazione e in cosa differisce da un requisito?",
 risposta="Il requisito dichiara che cosa la soluzione deve fare; il criterio di accettazione definisce la condizione verificabile che stabilisce se il requisito è stato soddisfatto. Un requisito senza criterio di accettazione non è collaudabile.",
 fonte="IIBA, BABOK Guide v3", riferimento="Acceptance and evaluation criteria"),
dict(id="BAB-10", tema="business_analysis", domanda="Che cos'è un Architecture Decision Record e quali sezioni contiene?",
 risposta="Un documento breve che registra una singola decisione architetturale: contesto e vincoli, opzioni considerate, decisione presa, motivazione e conseguenze, incluse quelle negative accettate. Serve a rendere ricostruibile il perché di una scelta a distanza di anni.",
 fonte="Nygard (2011), Documenting architecture decisions", riferimento="Formato ADR"),
dict(id="BAB-11", tema="business_analysis", domanda="Che cos'è la tracciabilità dei requisiti?",
 risposta="Il collegamento documentato di ogni requisito alla sua origine a monte (obiettivo di business, stakeholder) e ai suoi derivati a valle (design, codice, test). Rende possibile l'analisi d'impatto e dimostra la copertura in sede di verifica.",
 fonte="IIBA, BABOK Guide v3", riferimento="Trace requirements"),
dict(id="BAB-12", tema="business_analysis", domanda="Quali sono le cinque fasi del ciclo di vita ITIL 4 di un servizio, in termini di value stream?",
 risposta="ITIL 4 sostituisce il ciclo di vita lineare con il Service Value System: domanda e opportunità in ingresso, catena del valore con le attività Plan, Improve, Engage, Design & Transition, Obtain/Build, Deliver & Support, e valore in uscita.",
 fonte="ITIL 4 Foundation", riferimento="Service Value System e Service Value Chain"),
dict(id="BAB-13", tema="business_analysis", domanda="Qual è la differenza tra incident, problem e change nella gestione dei servizi?",
 risposta="L'incident è un'interruzione o degrado non pianificato del servizio e si gestisce ripristinando il servizio; il problem è la causa sottostante, potenziale o accertata, di uno o più incident; il change è l'aggiunta, modifica o rimozione di qualcosa che può avere effetto sui servizi.",
 fonte="ITIL 4 Foundation", riferimento="Practices: incident, problem e change enablement"),
dict(id="BAB-14", tema="business_analysis", domanda="Che cos'è il costo totale di proprietà e quali voci si dimenticano più spesso?",
 risposta="Il costo complessivo di una soluzione lungo il suo ciclo di vita. Le voci più spesso omesse sono migrazione dei dati, formazione, integrazione con i sistemi esistenti, manutenzione e supporto continuativi, costo del personale interno dedicato e costo di uscita a fine contratto.",
 fonte="Prassi di IT financial management; cfr. ITIL 4 — Service financial management", riferimento="TCO analysis"),
dict(id="BAB-15", tema="business_analysis", domanda="Che cos'è il vendor lock-in e con quali leve contrattuali si mitiga?",
 risposta="La dipendenza da un fornitore dovuta a costi di migrazione proibitivi. Si mitiga con clausole di portabilità ed esportazione dei dati in formati aperti, proprietà dei dati esplicitamente in capo al cliente, deposito del codice sorgente e assistenza contrattualmente dovuta in fase di uscita.",
 fonte="Prassi di procurement IT", riferimento="Exit management clauses"),
]
