# -*- coding: utf-8 -*-
"""Flashcard — lotto 2: ITIL 4, ISO/IEC 27001, DHIS2, HL7 FHIR, statistica applicata."""

FLASHCARD_C = [
# ===================================================== ITIL 4 (15)
dict(id="ITIL-01", tema="governance", domanda="Quali sono le quattro dimensioni della gestione dei servizi in ITIL 4?",
 risposta="Organizzazioni e persone; informazioni e tecnologia; partner e fornitori; flussi di valore e processi. Vanno considerate tutte e quattro per ogni servizio: trascurarne una produce servizi che funzionano tecnicamente ma falliscono nell'uso.",
 fonte="ITIL 4 Foundation", riferimento="Four dimensions of service management"),
dict(id="ITIL-02", tema="governance", domanda="Quali sono i sette principi guida di ITIL 4?",
 risposta="Concentrarsi sul valore; partire da dove si è; procedere iterativamente con feedback; collaborare e promuovere la visibilità; pensare e lavorare in modo olistico; mantenere le cose semplici e pratiche; ottimizzare e automatizzare.",
 fonte="ITIL 4 Foundation", riferimento="Guiding principles"),
dict(id="ITIL-03", tema="governance", domanda="Come definisce ITIL il «servizio»?",
 risposta="Un mezzo per abilitare la co-creazione di valore facilitando i risultati che i clienti vogliono ottenere, senza che debbano gestire costi e rischi specifici. Il valore non è consegnato dal fornitore: è co-creato con il cliente.",
 fonte="ITIL 4 Foundation", riferimento="Key concepts — service"),
dict(id="ITIL-04", tema="governance", domanda="Che differenza c'è tra utilità e garanzia?",
 risposta="L'utilità è ciò che il servizio fa, cioè l'idoneità allo scopo; la garanzia è come lo fa, cioè l'idoneità all'uso — disponibilità, capacità, continuità, sicurezza. Servono entrambe: un servizio utile ma inaffidabile non produce valore.",
 fonte="ITIL 4 Foundation", riferimento="Utility and warranty"),
dict(id="ITIL-05", tema="governance", domanda="Quali sono le sei attività della catena del valore del servizio?",
 risposta="Plan, Improve, Engage, Design & Transition, Obtain/Build, Deliver & Support. Non sono una sequenza fissa: ogni flusso di valore le combina nell'ordine che gli serve.",
 fonte="ITIL 4 Foundation", riferimento="Service value chain"),
dict(id="ITIL-06", tema="governance", domanda="Quali sono i tre tipi di change enablement?",
 risposta="Standard (preautorizzato, a basso rischio, procedura nota); normale (valutato e autorizzato secondo il percorso previsto); emergenza (percorso accelerato per ripristinare un servizio o evitare un impatto grave, con autorizzazione a posteriori della documentazione).",
 fonte="ITIL 4 Foundation", riferimento="Change enablement practice"),
dict(id="ITIL-07", tema="governance", domanda="Che cos'è un known error e come si collega a workaround e problem?",
 risposta="Un problema di cui sono stati analizzati causa e workaround ma che non è ancora risolto in modo definitivo. Il workaround riduce l'impatto senza eliminare la causa; il known error consente al service desk di ripristinare rapidamente i servizi in attesa della correzione strutturale.",
 fonte="ITIL 4 Foundation", riferimento="Problem management practice"),
dict(id="ITIL-08", tema="governance", domanda="Che cos'è il service desk e qual è la sua funzione che va oltre il supporto tecnico?",
 risposta="È il punto unico di contatto fra fornitore e utenti. La sua funzione che conta di più non è tecnica ma relazionale: è il canale attraverso cui l'organizzazione percepisce la qualità del servizio e attraverso cui si raccolgono i segnali deboli di problemi emergenti.",
 fonte="ITIL 4 Foundation", riferimento="Service desk practice"),
dict(id="ITIL-09", tema="governance", domanda="Qual è la differenza tra service request e incident?",
 risposta="La richiesta di servizio è una domanda preventivata e normale dell'utente — un accesso, un dispositivo, un'informazione — e segue un flusso standardizzato; l'incident è un'interruzione o degrado non pianificato e ha come obiettivo il ripristino nel minor tempo possibile.",
 fonte="ITIL 4 Foundation", riferimento="Service request management"),
dict(id="ITIL-10", tema="governance", domanda="Quali sono i passi del modello di miglioramento continuo ITIL?",
 risposta="Qual è la visione? Dove siamo ora? Dove vogliamo arrivare? Come ci arriviamo? Agire. Abbiamo raggiunto l'obiettivo? Come manteniamo lo slancio? Il passo più saltato — e più importante — è il secondo.",
 fonte="ITIL 4 Foundation", riferimento="Continual improvement model"),
dict(id="ITIL-11", tema="governance", domanda="Che cos'è un catalogo dei servizi e perché è il primo documento che un nuovo responsabile IT dovrebbe produrre?",
 risposta="L'elenco strutturato dei servizi erogati con descrizione, destinatari, livelli di servizio e proprietario. È il primo perché rende esplicito ciò che l'organizzazione si aspetta implicitamente, e trasforma richieste arbitrarie in servizi con confini negoziati.",
 fonte="ITIL 4 Foundation", riferimento="Service catalogue management"),
dict(id="ITIL-12", tema="governance", domanda="Che cos'è il service level management e qual è l'errore più comune nel definire gli SLA?",
 risposta="La pratica che definisce, concorda e monitora i livelli di servizio. L'errore più comune è misurare ciò che è facile — disponibilità del sistema — invece di ciò che l'utente sperimenta, producendo la situazione in cui tutti gli SLA sono verdi mentre gli utenti sono insoddisfatti (watermelon SLA).",
 fonte="ITIL 4 Foundation", riferimento="Service level management practice"),
dict(id="ITIL-13", tema="governance", domanda="Che cos'è la configuration management database e quale insidia comporta?",
 risposta="Il repository degli elementi di configurazione e delle loro relazioni. L'insidia è l'ambizione di completezza: una CMDB che tenta di censire tutto diventa immediatamente obsoleta. Va limitata agli elementi le cui relazioni servono davvero per analisi d'impatto.",
 fonte="ITIL 4 Foundation", riferimento="Service configuration management"),
dict(id="ITIL-14", tema="governance", domanda="Che differenza c'è tra disponibilità e continuità del servizio?",
 risposta="La disponibilità riguarda il funzionamento del servizio nelle condizioni ordinarie e si misura in percentuale di tempo utile; la continuità riguarda la capacità di erogare un livello minimo concordato dopo un evento disastroso, e si misura in RTO e RPO.",
 fonte="ITIL 4 Foundation", riferimento="Availability e service continuity management"),
dict(id="ITIL-15", tema="governance", domanda="Che cos'è la governance nel Service Value System e in cosa differisce dal management?",
 risposta="La governance è il sistema con cui l'organizzazione è diretta e controllata: valuta, indirizza e monitora. Il management esegue all'interno di quella direzione. Confondere i due livelli è la causa più comune di funzioni IT che operano senza mandato.",
 fonte="ITIL 4 Foundation; cfr. ISO/IEC 38500", riferimento="Governance in the SVS"),

# ===================================================== ISO/IEC 27001 (15)
dict(id="ISO-01", tema="sicurezza", domanda="Che cos'è un ISMS secondo la ISO/IEC 27001?",
 risposta="Un sistema di gestione della sicurezza delle informazioni: un insieme documentato di politiche, processi e controlli, con ambito definito, guidato dal rischio e soggetto a miglioramento continuo secondo il ciclo Plan-Do-Check-Act.",
 fonte="ISO/IEC 27001:2022", riferimento="Clausole 4-10"),
dict(id="ISO-02", tema="sicurezza", domanda="Quali sono i tre attributi fondamentali della sicurezza delle informazioni?",
 risposta="Riservatezza, integrità e disponibilità. Molti quadri aggiungono autenticità, non ripudio e tracciabilità, ma i tre restano il nucleo rispetto a cui si classifica ogni rischio.",
 fonte="ISO/IEC 27000", riferimento="Termini e definizioni"),
dict(id="ISO-03", tema="sicurezza", domanda="Come sono organizzati i controlli dell'Allegato A nella versione 2022?",
 risposta="In quattro temi: organizzativi, relativi alle persone, fisici e tecnologici, per un totale di 93 controlli, rispetto agli oltre cento raggruppati in quattordici categorie della versione precedente.",
 fonte="ISO/IEC 27001:2022", riferimento="Annex A"),
dict(id="ISO-04", tema="sicurezza", domanda="Che cos'è la Dichiarazione di Applicabilità e perché è il documento centrale della certificazione?",
 risposta="Il documento che elenca tutti i controlli dell'Allegato A indicando quali si applicano, come sono attuati e, per gli esclusi, la giustificazione dell'esclusione. È centrale perché collega esplicitamente la valutazione del rischio alle misure adottate.",
 fonte="ISO/IEC 27001:2022", riferimento="Clausola 6.1.3 d"),
dict(id="ISO-05", tema="sicurezza", domanda="Quali sono le quattro opzioni di trattamento del rischio?",
 risposta="Modificare il rischio applicando controlli; mantenerlo accettandolo consapevolmente; evitarlo eliminando l'attività che lo genera; condividerlo tramite assicurazione o esternalizzazione. Nessuna delle quattro è di per sé sbagliata: sbagliato è non decidere.",
 fonte="ISO/IEC 27005", riferimento="Risk treatment options"),
dict(id="ISO-06", tema="sicurezza", domanda="Che differenza c'è tra ISO/IEC 27001 e ISO/IEC 27002?",
 risposta="La 27001 contiene i requisiti certificabili del sistema di gestione; la 27002 è una guida che descrive come attuare i singoli controlli. Ci si certifica sulla 27001, si lavora con la 27002 in mano.",
 fonte="ISO/IEC 27001:2022 e 27002:2022", riferimento="Rapporto fra le norme"),
dict(id="ISO-07", tema="sicurezza", domanda="Che cos'è la ISO/IEC 27701 e a chi serve?",
 risposta="Un'estensione della 27001 e della 27002 per la gestione delle informazioni sulla privacy, che introduce requisiti e controlli per titolari e responsabili del trattamento. Serve a chi vuole dimostrare in modo certificabile l'allineamento fra sicurezza e protezione dei dati personali.",
 fonte="ISO/IEC 27701", riferimento="Privacy information management extension"),
dict(id="ISO-08", tema="sicurezza", domanda="Cita almeno cinque controlli introdotti nella revisione 2022.",
 risposta="Threat intelligence; sicurezza per l'uso di servizi cloud; preparazione ICT per la continuità operativa; monitoraggio della sicurezza fisica; gestione della configurazione; cancellazione delle informazioni; mascheramento dei dati; prevenzione della fuga di dati; attività di monitoraggio; filtraggio web; codifica sicura.",
 fonte="ISO/IEC 27001:2022", riferimento="Annex A — nuovi controlli"),
dict(id="ISO-09", tema="sicurezza", domanda="Che cos'è il principio del minimo privilegio e come si verifica nella pratica?",
 risposta="Ogni utente o processo dispone dei soli permessi necessari alle sue funzioni, per il solo tempo necessario. Si verifica con revisioni periodiche degli accessi, confrontando i permessi effettivi con i ruoli dichiarati e rimuovendo quelli accumulati per cambi di mansione.",
 fonte="ISO/IEC 27002:2022", riferimento="Controllo — Access rights"),
dict(id="ISO-10", tema="sicurezza", domanda="Che cos'è la separazione dei compiti e quale rischio mitiga?",
 risposta="La suddivisione di attività critiche fra persone diverse in modo che nessuno possa completare da solo un'azione ad alto impatto. Mitiga sia la frode sia l'errore: chi sviluppa non dovrebbe poter rilasciare in produzione senza un secondo controllo.",
 fonte="ISO/IEC 27002:2022", riferimento="Controllo — Segregation of duties"),
dict(id="ISO-11", tema="sicurezza", domanda="Che cos'è una non conformità maggiore in un audit di certificazione?",
 risposta="L'assenza totale di un requisito, o un fallimento sistematico che compromette la capacità dell'ISMS di raggiungere i propri obiettivi. Blocca la certificazione fino alla risoluzione, a differenza della minore che si gestisce con un piano di azione correttiva.",
 fonte="ISO/IEC 17021 / prassi di audit", riferimento="Classificazione dei rilievi"),
dict(id="ISO-12", tema="sicurezza", domanda="Che cos'è il rischio residuo e chi lo approva?",
 risposta="Il rischio che permane dopo l'applicazione dei controlli. Deve essere valutato, documentato e approvato formalmente dalla direzione: è una decisione di business, non una scelta tecnica del responsabile della sicurezza.",
 fonte="ISO/IEC 27001:2022", riferimento="Clausola 6.1.3 e-f"),
dict(id="ISO-13", tema="sicurezza", domanda="Che cos'è la classificazione delle informazioni e perché precede ogni altro controllo?",
 risposta="L'attribuzione di un livello di sensibilità a ciascuna informazione, con regole di trattamento associate. Precede gli altri controlli perché senza sapere cosa si protegge e quanto vale, ogni misura è o sovradimensionata o insufficiente.",
 fonte="ISO/IEC 27002:2022", riferimento="Controllo — Classification of information"),
dict(id="ISO-14", tema="sicurezza", domanda="Che cos'è la NIS2 e in che cosa differisce dalla ISO/IEC 27001?",
 risposta="È una direttiva europea che impone obblighi di gestione del rischio informatico e di notifica degli incidenti a soggetti essenziali e importanti in settori individuati, con responsabilità diretta degli organi di gestione. La 27001 è una norma volontaria e certificabile; la NIS2 è legge, e la conformità alla norma può supportarla ma non la sostituisce.",
 fonte="Direttiva (UE) 2022/2555", riferimento="NIS2 — obblighi e ambito"),
dict(id="ISO-15", tema="sicurezza", domanda="Qual è la sequenza corretta delle fasi di risposta a un incidente di sicurezza?",
 risposta="Preparazione; rilevazione e analisi; contenimento, eradicazione e ripristino; attività post-incidente. La fase più trascurata è la prima, e quella che determina il valore di lungo periodo è l'ultima.",
 fonte="NIST SP 800-61 Rev. 2", riferimento="Computer security incident handling guide"),

# ===================================================== DHIS2 (12)
dict(id="DHIS-01", tema="salute_digitale", domanda="Che cos'è un data element in DHIS2?",
 risposta="L'unità atomica di raccolta: ciò che viene effettivamente registrato, per esempio «casi di malaria confermati». È distinto dall'indicatore, che è una formula calcolata a partire da data element.",
 fonte="DHIS2 — documentazione ufficiale", riferimento="Data elements"),
dict(id="DHIS-02", tema="salute_digitale", domanda="Qual è la differenza tra data element e indicator in DHIS2?",
 risposta="Il data element è un dato grezzo raccolto; l'indicator è una formula con numeratore e denominatore, calcolata a runtime, che produce tassi, percentuali e rapporti. Gli indicator non si raccolgono: si derivano.",
 fonte="DHIS2 — documentazione ufficiale", riferimento="Indicators"),
dict(id="DHIS-03", tema="salute_digitale", domanda="Che cos'è una category combination e a che cosa serve?",
 risposta="Un meccanismo di disaggregazione che moltiplica un data element per una o più dimensioni — per esempio sesso ed età — generando le combinazioni effettive di raccolta. Evita di creare manualmente un data element per ogni combinazione.",
 fonte="DHIS2 — documentazione ufficiale", riferimento="Category combinations"),
dict(id="DHIS-04", tema="salute_digitale", domanda="Che cos'è la gerarchia delle organisation unit?",
 risposta="L'albero delle unità organizzative — paese, regione, distretto, struttura — che definisce la dimensione geografica di ogni dato. È la dimensione conforme per eccellenza del sistema: cambiarla a posteriori è l'operazione più costosa in DHIS2.",
 fonte="DHIS2 — documentazione ufficiale", riferimento="Organisation unit hierarchy"),
dict(id="DHIS-05", tema="salute_digitale", domanda="Qual è la differenza tra dati aggregati e Tracker in DHIS2?",
 risposta="I dati aggregati registrano conteggi per unità organizzativa e periodo; il Tracker segue singole entità nel tempo, con eventi e stadi di programma. Il Tracker comporta dati individuali e quindi un regime di protezione dei dati completamente diverso.",
 fonte="DHIS2 — documentazione ufficiale", riferimento="Aggregate vs tracker data models"),
dict(id="DHIS-06", tema="salute_digitale", domanda="Che cos'è un data set in DHIS2?",
 risposta="Un insieme di data element raccolti insieme con la stessa periodicità e assegnati a specifiche unità organizzative: corrisponde in pratica al modulo di raccolta.",
 fonte="DHIS2 — documentazione ufficiale", riferimento="Data sets"),
dict(id="DHIS-07", tema="salute_digitale", domanda="Che cosa sono le analytics tables e perché il dato nuovo non compare subito nei cruscotti?",
 risposta="Sono tabelle precalcolate generate da un processo periodico per rendere veloci le interrogazioni analitiche. Finché l'analytics non viene rigenerata, i dati appena inseriti non compaiono nei report: è la causa più frequente di segnalazioni di «dato mancante» che non sono errori.",
 fonte="DHIS2 — documentazione ufficiale", riferimento="Analytics tables generation"),
dict(id="DHIS-08", tema="salute_digitale", domanda="Quali strumenti di qualità del dato offre DHIS2 nativamente?",
 risposta="Regole di validazione fra data element, analisi min-max per valori anomali, analisi degli outlier basata su deviazione standard o scarto interquartile, controllo di completezza e tempestività della segnalazione, e analisi di follow-up.",
 fonte="DHIS2 — documentazione ufficiale", riferimento="Data quality module"),
dict(id="DHIS-09", tema="salute_digitale", domanda="Come funziona la raccolta offline con l'app Android di DHIS2?",
 risposta="I metadati vengono scaricati e memorizzati localmente; la raccolta avviene nel database locale del dispositivo e la sincronizzazione è avviata quando torna la connettività. Ne consegue che i metadati devono essere stabili: una modifica lato server durante una missione crea conflitti di sincronizzazione.",
 fonte="DHIS2 Android Capture — documentazione", riferimento="Offline capability e sincronizzazione"),
dict(id="DHIS-10", tema="salute_digitale", domanda="Qual è l'endpoint API principale per l'invio di dati aggregati?",
 risposta="Il servizio dataValueSets dell'API web, che accetta insiemi di valori in JSON, XML o CSV identificati da data element, periodo, unità organizzativa e combinazione di categoria; per il Tracker si usano invece gli endpoint dedicati agli eventi e alle entità tracciate.",
 fonte="DHIS2 — Web API documentation", riferimento="Data values — dataValueSets"),
dict(id="DHIS-11", tema="salute_digitale", domanda="Che cosa sono i WHO metadata package per DHIS2?",
 risposta="Pacchetti di metadati preconfigurati e allineati agli standard OMS per specifici programmi — sorveglianza, immunizzazione, salute materna — che permettono di avviare un sistema con definizioni standardizzate invece di costruirle da zero.",
 fonte="DHIS2 / WHO — metadata packages", riferimento="Standard configuration packages"),
dict(id="DHIS-12", tema="salute_digitale", domanda="Perché la scelta del period type in DHIS2 è una decisione difficilmente reversibile?",
 risposta="Perché determina la granularità con cui il dato viene storicizzato: passare da mensile a settimanale non consente di disaggregare retroattivamente i dati già raccolti, mentre il percorso inverso perde definitivamente il dettaglio.",
 fonte="DHIS2 — documentazione ufficiale", riferimento="Period types"),

# ===================================================== HL7 FHIR (12)
dict(id="FHIR-01", tema="salute_digitale", domanda="Che cos'è FHIR e su quali principi è costruito?",
 risposta="Uno standard HL7 per lo scambio di informazioni sanitarie basato su risorse modulari, API REST e formati web comuni come JSON e XML. Il principio guida è che l'80% dei casi d'uso sia coperto dal nucleo della risorsa, lasciando il resto alle estensioni.",
 fonte="HL7 FHIR — specifica ufficiale", riferimento="Overview e principi di design"),
dict(id="FHIR-02", tema="salute_digitale", domanda="Che cos'è una risorsa FHIR?",
 risposta="L'unità atomica di scambio: un oggetto identificabile con un tipo definito, un identificativo, un contenuto strutturato e una rappresentazione standard. Patient, Encounter, Observation e Condition sono fra le più usate.",
 fonte="HL7 FHIR — specifica ufficiale", riferimento="Resource definitions"),
dict(id="FHIR-03", tema="salute_digitale", domanda="Quali risorse FHIR corrispondono a paziente, visita, diagnosi, esame e vaccinazione?",
 risposta="Rispettivamente Patient, Encounter, Condition, Observation e Immunization.",
 fonte="HL7 FHIR — specifica ufficiale", riferimento="Clinical resources"),
dict(id="FHIR-04", tema="salute_digitale", domanda="Che cos'è un Bundle in FHIR?",
 risposta="Un contenitore che raggruppa più risorse in un unico messaggio: si usa per risultati di ricerca, documenti, messaggi e transazioni atomiche in cui tutte le operazioni riescono o falliscono insieme.",
 fonte="HL7 FHIR — specifica ufficiale", riferimento="Bundle resource"),
dict(id="FHIR-05", tema="salute_digitale", domanda="Che cos'è un profilo FHIR e perché è quasi sempre necessario?",
 risposta="Una restrizione o estensione di una risorsa base che vincola cardinalità, terminologie e campi obbligatori per un contesto specifico. È necessario perché la risorsa base è deliberatamente permissiva: senza profilo, due sistemi «conformi a FHIR» possono restare incompatibili.",
 fonte="HL7 FHIR — specifica ufficiale", riferimento="Profiling e StructureDefinition"),
dict(id="FHIR-06", tema="salute_digitale", domanda="Che cos'è una Implementation Guide?",
 risposta="Un insieme coerente e pubblicato di profili, terminologie, esempi e regole di conformità che definisce come FHIR va usato in un dato dominio o giurisdizione. È il documento su cui si verifica l'interoperabilità reale.",
 fonte="HL7 FHIR — specifica ufficiale", riferimento="Implementation guides"),
dict(id="FHIR-07", tema="salute_digitale", domanda="Che cos'è un CodeableConcept?",
 risposta="Un tipo di dato che rappresenta un concetto clinico con uno o più codici provenienti da sistemi terminologici, più un eventuale testo libero. Permette di trasportare contemporaneamente la codifica formale e la dicitura originale.",
 fonte="HL7 FHIR — specifica ufficiale", riferimento="Data types — CodeableConcept"),
dict(id="FHIR-08", tema="salute_digitale", domanda="Qual è la differenza d'uso fra ICD-10, SNOMED CT e LOINC?",
 risposta="ICD-10 classifica diagnosi e cause di morte a fini statistici ed epidemiologici; SNOMED CT è una terminologia clinica granulare per la documentazione del caso; LOINC identifica esami di laboratorio e osservazioni. Non sono alternative: coprono livelli diversi.",
 fonte="WHO ICD-10; SNOMED International; Regenstrief LOINC", riferimento="Ambiti d'uso delle terminologie"),
dict(id="FHIR-09", tema="salute_digitale", domanda="Che differenza c'è tra HL7 versione 2 e FHIR?",
 risposta="HL7 v2 usa messaggi con segmenti delimitati da barre verticali, orientati all'evento e molto diffusi nei sistemi ospedalieri esistenti; FHIR usa risorse e API REST ed è pensato per il web e il mobile. Molte integrazioni reali fanno convivere i due con un livello di traduzione.",
 fonte="HL7 — specifiche v2 e FHIR", riferimento="Confronto fra standard"),
dict(id="FHIR-10", tema="salute_digitale", domanda="Che cos'è ICD-11 e qual è la differenza strutturale rispetto a ICD-10?",
 risposta="La revisione più recente della classificazione OMS, progettata come sistema digitale con una fondazione ontologica che consente codifica post-coordinata tramite estensioni, anziché la sola struttura gerarchica a codici fissi di ICD-10.",
 fonte="WHO ICD-11", riferimento="Reference guide"),
dict(id="FHIR-11", tema="salute_digitale", domanda="Perché i dati FHIR non sono per definizione anonimi?",
 risposta="Perché le risorse cliniche contengono riferimenti incrociati e dettagli temporali e geografici che permettono la re-identificazione anche in assenza di nome. La de-identificazione richiede un intervento esplicito su identificativi, date e granularità geografica.",
 fonte="HL7 FHIR — Security and privacy module", riferimento="De-identification"),
dict(id="FHIR-12", tema="salute_digitale", domanda="Che cos'è SMART on FHIR?",
 risposta="Un profilo che combina FHIR con OAuth 2.0 e OpenID Connect per consentire ad applicazioni di terze parti di accedere in modo autorizzato ai dati clinici, con ambiti di accesso espliciti e consenso dell'utente.",
 fonte="SMART Health IT / HL7", riferimento="SMART App Launch framework"),

# ===================================================== STATISTICA (26)
dict(id="STAT-01", tema="statistica", domanda="Quando la mediana è preferibile alla media?",
 risposta="Quando la distribuzione è asimmetrica o contiene valori estremi: la media viene trascinata dalla coda, la mediana no. Per tempi di attesa, costi e redditi la mediana descrive meglio il caso tipico.",
 fonte="Statistica descrittiva — testi standard", riferimento="Misure di tendenza centrale"),
dict(id="STAT-02", tema="statistica", domanda="Qual è la differenza tra deviazione standard ed errore standard?",
 risposta="La deviazione standard misura la dispersione dei valori nella popolazione o nel campione; l'errore standard misura la precisione della stima di un parametro e diminuisce all'aumentare della numerosità campionaria. Confonderli porta a intervalli di confidenza sbagliati.",
 fonte="Statistica inferenziale — testi standard", riferimento="Standard deviation vs standard error"),
dict(id="STAT-03", tema="statistica", domanda="Che cosa significa esattamente un intervallo di confidenza al 95%?",
 risposta="Che se si ripetesse il campionamento molte volte con lo stesso metodo, circa il 95% degli intervalli così costruiti conterrebbe il valore vero. Non significa che ci sia il 95% di probabilità che il valore vero stia in quel particolare intervallo.",
 fonte="Statistica inferenziale — testi standard", riferimento="Interpretazione degli intervalli di confidenza"),
dict(id="STAT-04", tema="statistica", domanda="Che cosa misura un valore p e che cosa non misura?",
 risposta="Misura la probabilità di osservare dati almeno altrettanto estremi assumendo vera l'ipotesi nulla. Non misura la probabilità che l'ipotesi nulla sia vera, né la dimensione dell'effetto, né la sua rilevanza pratica.",
 fonte="American Statistical Association", riferimento="Statement on p-values (2016)"),
dict(id="STAT-05", tema="statistica", domanda="Qual è la differenza tra errore di primo e di secondo tipo?",
 risposta="Il primo tipo è rifiutare un'ipotesi nulla vera, cioè vedere un effetto che non c'è; il secondo tipo è non rifiutare un'ipotesi nulla falsa, cioè non vedere un effetto reale. Ridurre uno aumenta l'altro a parità di numerosità.",
 fonte="Statistica inferenziale — testi standard", riferimento="Verifica delle ipotesi"),
dict(id="STAT-06", tema="statistica", domanda="Che cos'è la potenza statistica e da che cosa dipende?",
 risposta="La probabilità di rilevare un effetto reale della dimensione ipotizzata. Dipende dalla numerosità campionaria, dalla dimensione dell'effetto, dalla variabilità e dal livello di significatività scelto. Uno studio sottodimensionato non «dimostra l'assenza di effetto».",
 fonte="Statistica inferenziale — testi standard", riferimento="Power analysis"),
dict(id="STAT-07", tema="statistica", domanda="Che cos'è il design effect in un'indagine a grappoli?",
 risposta="Il fattore per cui va moltiplicata la numerosità campionaria rispetto a un campionamento casuale semplice, per compensare la minore variabilità interna ai grappoli. Ignorarlo produce intervalli di confidenza artificiosamente stretti.",
 fonte="Metodologia SMART / indagini a grappoli", riferimento="Design effect e calcolo campionario"),
dict(id="STAT-08", tema="statistica", domanda="Come è strutturata un'indagine SMART?",
 risposta="Tipicamente come un campionamento a grappoli in due stadi: nel primo si selezionano i grappoli con probabilità proporzionale alla dimensione, nel secondo si selezionano le famiglie all'interno del grappolo. Serve a stimare prevalenza di malnutrizione e tassi di mortalità.",
 fonte="SMART Methodology", riferimento="Sampling design"),
dict(id="STAT-09", tema="statistica", domanda="Qual è la differenza tra prevalenza e incidenza?",
 risposta="La prevalenza è la proporzione di casi esistenti in una popolazione in un dato momento; l'incidenza è il numero di casi nuovi che insorgono in un intervallo, rapportato alla popolazione a rischio. La prevalenza dipende anche dalla durata della condizione.",
 fonte="Epidemiologia — testi standard", riferimento="Misure di frequenza"),
dict(id="STAT-10", tema="statistica", domanda="Qual è la differenza tra proporzione, rapporto e tasso?",
 risposta="Nella proporzione il numeratore è incluso nel denominatore; nel rapporto le due quantità sono indipendenti; nel tasso il denominatore incorpora una dimensione temporale, come persona-tempo a rischio.",
 fonte="Epidemiologia — testi standard", riferimento="Misure di frequenza"),
dict(id="STAT-11", tema="statistica", domanda="Che cos'è il confondimento?",
 risposta="La distorsione di un'associazione dovuta a una terza variabile associata sia all'esposizione sia all'esito, senza essere un anello causale intermedio. Si controlla per disegno, con restrizione o appaiamento, oppure in analisi con stratificazione o modelli multivariati.",
 fonte="Epidemiologia — testi standard", riferimento="Confounding"),
dict(id="STAT-12", tema="statistica", domanda="Che cos'è il paradosso di Simpson?",
 risposta="Il fenomeno per cui un'associazione osservata nei dati aggregati si inverte quando si analizzano i sottogruppi. È la manifestazione più drammatica del confondimento e la ragione per cui un dato aggregato senza disaggregazione può indurre in errore.",
 fonte="Simpson (1951)", riferimento="The interpretation of interaction in contingency tables"),
dict(id="STAT-13", tema="statistica", domanda="Che cos'è la regressione verso la media e come genera falsi successi?",
 risposta="La tendenza di valori estremi a essere seguiti da valori più vicini alla media per effetto della sola variabilità casuale. Un intervento avviato dove la situazione era peggiore mostrerà un miglioramento anche se è totalmente inefficace.",
 fonte="Statistica — testi standard; Kahneman, Thinking Fast and Slow", riferimento="Regression to the mean"),
dict(id="STAT-14", tema="statistica", domanda="Che cos'è il bias di selezione?",
 risposta="La distorsione che nasce quando il modo di selezionare i soggetti è associato sia all'esposizione sia all'esito, rendendo il campione non rappresentativo rispetto alla domanda posta. Nessuna dimensione campionaria lo corregge.",
 fonte="Epidemiologia — testi standard", riferimento="Selection bias"),
dict(id="STAT-15", tema="statistica", domanda="Che cos'è il bias del sopravvissuto e come si manifesta nei dati di programma?",
 risposta="La distorsione dovuta all'analisi dei soli casi che sono rimasti osservabili. Nei dati di programma si manifesta valutando gli esiti solo di chi ha completato il percorso, escludendo abbandoni e trasferimenti che sono spesso proprio gli esiti peggiori.",
 fonte="Metodologia della ricerca", riferimento="Survivorship bias"),
dict(id="STAT-16", tema="statistica", domanda="Quali sono i tre meccanismi di dato mancante?",
 risposta="Completamente casuale, quando l'assenza è indipendente da tutto; casuale condizionatamente, quando dipende da variabili osservate; non casuale, quando dipende dal valore mancante stesso. Solo i primi due si gestiscono adeguatamente con le tecniche standard di imputazione.",
 fonte="Rubin (1976); Little & Rubin", riferimento="MCAR, MAR, MNAR"),
dict(id="STAT-17", tema="statistica", domanda="Perché sostituire i valori mancanti con la media è una pratica sconsigliata?",
 risposta="Perché riduce artificiosamente la varianza, attenua le correlazioni e produce intervalli di confidenza troppo stretti, dando una falsa impressione di precisione. È preferibile l'imputazione multipla o l'esplicita esclusione documentata.",
 fonte="Little & Rubin, Statistical Analysis with Missing Data", riferimento="Single imputation — limiti"),
dict(id="STAT-18", tema="statistica", domanda="Qual è la differenza tra un valore anomalo e un errore?",
 risposta="L'anomalo è un valore estremo ma potenzialmente vero, che può contenere l'informazione più importante del dataset; l'errore è un valore sbagliato. Eliminare gli anomali senza indagarli è il modo più rapido per cancellare un segnale epidemiologico reale.",
 fonte="Statistica esplorativa — testi standard", riferimento="Outlier analysis"),
dict(id="STAT-19", tema="statistica", domanda="Che cos'è lo scarto interquartile e perché è preferito nella rilevazione di anomalie su dati asimmetrici?",
 risposta="La differenza fra terzo e primo quartile. È preferito perché non dipende dall'ipotesi di normalità e non viene esso stesso trascinato dai valori estremi, a differenza della regola basata sulle deviazioni standard.",
 fonte="Tukey, Exploratory Data Analysis", riferimento="IQR e boxplot"),
dict(id="STAT-20", tema="statistica", domanda="Che cos'è l'asimmetria di una distribuzione e che effetto ha sull'analisi?",
 risposta="La misura in cui la distribuzione si allunga da un lato. Con forte asimmetria positiva media e mediana divergono, i test che assumono normalità perdono validità, e spesso conviene una trasformazione o un metodo non parametrico.",
 fonte="Statistica descrittiva — testi standard", riferimento="Skewness"),
dict(id="STAT-21", tema="statistica", domanda="Che cos'è uno z-score?",
 risposta="Il numero di deviazioni standard che separano un valore dalla media di riferimento. In ambito nutrizionale gli z-score rispetto agli standard di crescita OMS sono il criterio per classificare la malnutrizione acuta.",
 fonte="WHO Child Growth Standards", riferimento="Z-scores e classificazione nutrizionale"),
dict(id="STAT-22", tema="statistica", domanda="Perché correlazione non implica causalità, e quali criteri aiutano a valutare la plausibilità causale?",
 risposta="Perché l'associazione può derivare da confondimento, causalità inversa o caso. I criteri di Bradford Hill — forza, coerenza, specificità, temporalità, gradiente, plausibilità, coerenza teorica, evidenza sperimentale, analogia — offrono un quadro di valutazione, non una prova.",
 fonte="Bradford Hill (1965)", riferimento="The environment and disease: association or causation?"),
dict(id="STAT-23", tema="statistica", domanda="Che cos'è il campionamento con probabilità proporzionale alla dimensione?",
 risposta="Un metodo in cui la probabilità di selezione di un'unità primaria è proporzionale alla sua popolazione, così che ogni individuo abbia la stessa probabilità complessiva di essere selezionato nel disegno a due stadi.",
 fonte="Metodologia del campionamento", riferimento="PPS sampling"),
dict(id="STAT-24", tema="statistica", domanda="Che cos'è il sampling frame e qual è l'errore che genera quando è incompleto?",
 risposta="L'elenco da cui si estrae il campione. Se non copre l'intera popolazione target genera errore di copertura: le unità escluse hanno probabilità zero di essere selezionate e nessuna ponderazione a posteriori può correggere l'omissione.",
 fonte="Metodologia del campionamento", riferimento="Coverage error"),
dict(id="STAT-25", tema="statistica", domanda="Che cos'è la standardizzazione di un tasso e perché serve nel confronto fra popolazioni?",
 risposta="L'aggiustamento di un tasso grezzo rispetto a una struttura di popolazione di riferimento, tipicamente per età. Serve perché due popolazioni con strutture demografiche diverse producono tassi grezzi non confrontabili anche a parità di rischio effettivo.",
 fonte="Epidemiologia — testi standard", riferimento="Direct e indirect standardization"),
dict(id="STAT-26", tema="statistica", domanda="Perché un aumento del numero registrato di casi non equivale a un aumento dell'incidenza?",
 risposta="Perché può riflettere un cambiamento nella capacità di rilevazione: più strutture attive, migliore accesso, nuovi criteri diagnostici o semplicemente una migliore segnalazione. Senza denominatore e senza sforzo di sorveglianza costante, la serie storica non è interpretabile.",
 fonte="Epidemiologia — sorveglianza", riferimento="Artefatti di sorveglianza"),
]
