# -*- coding: utf-8 -*-
"""Flashcard verificabili — ogni scheda porta la fonte autorevole per il controllo indipendente."""

FLASHCARD_A = [
# ================================================================= GDPR
dict(id="GDPR-01", tema="gdpr", domanda="Come definisce il GDPR il «dato personale»?",
 risposta="Qualsiasi informazione riguardante una persona fisica identificata o identificabile, direttamente o indirettamente, in particolare mediante riferimento a un identificativo (nome, numero, dati di ubicazione, identificativo online) o a elementi caratteristici della sua identità fisica, fisiologica, genetica, psichica, economica, culturale o sociale.",
 fonte="Regolamento (UE) 2016/679", riferimento="Art. 4, punto 1"),
dict(id="GDPR-02", tema="gdpr", domanda="Che cos'è la pseudonimizzazione secondo il GDPR e perché non equivale all'anonimizzazione?",
 risposta="È il trattamento dei dati in modo che non possano più essere attribuiti a un interessato senza informazioni aggiuntive, conservate separatamente e protette. Resta un dato personale a tutti gli effetti e continua a ricadere sotto il GDPR; l'anonimizzazione irreversibile invece esce dall'ambito del Regolamento.",
 fonte="Regolamento (UE) 2016/679", riferimento="Art. 4, punto 5; Considerando 26"),
dict(id="GDPR-03", tema="gdpr", domanda="Quali sono i sei principi del trattamento previsti dall'art. 5, paragrafo 1?",
 risposta="Liceità, correttezza e trasparenza; limitazione della finalità; minimizzazione dei dati; esattezza; limitazione della conservazione; integrità e riservatezza.",
 fonte="Regolamento (UE) 2016/679", riferimento="Art. 5, par. 1, lett. a-f"),
dict(id="GDPR-04", tema="gdpr", domanda="Che cosa aggiunge l'art. 5, paragrafo 2 ai sei principi?",
 risposta="Il principio di responsabilizzazione (accountability): il titolare non deve solo rispettare i principi, ma essere in grado di dimostrarne il rispetto.",
 fonte="Regolamento (UE) 2016/679", riferimento="Art. 5, par. 2"),
dict(id="GDPR-05", tema="gdpr", domanda="Quali sono le sei basi giuridiche del trattamento?",
 risposta="Consenso; esecuzione di un contratto; obbligo legale; interesse vitale; compito di interesse pubblico o esercizio di pubblici poteri; legittimo interesse del titolare o di terzi.",
 fonte="Regolamento (UE) 2016/679", riferimento="Art. 6, par. 1, lett. a-f"),
dict(id="GDPR-06", tema="gdpr", domanda="I dati sanitari rientrano in quale categoria e qual è la regola generale?",
 risposta="Sono categorie particolari di dati. La regola generale è il divieto di trattamento, salvo che ricorra una delle eccezioni tassative del paragrafo 2. Serve quindi sia una base dell'art. 6 sia un'eccezione dell'art. 9.",
 fonte="Regolamento (UE) 2016/679", riferimento="Art. 9, par. 1 e 2"),
dict(id="GDPR-07", tema="gdpr", domanda="Quali eccezioni dell'art. 9, par. 2 sono più rilevanti per un'organizzazione medico-umanitaria?",
 risposta="Consenso esplicito (lett. a); interesse vitale quando l'interessato è incapace di prestare consenso (lett. c); finalità di medicina preventiva, diagnosi e assistenza sanitaria (lett. h); interesse pubblico nel settore della sanità pubblica (lett. i); ricerca scientifica e statistica (lett. j).",
 fonte="Regolamento (UE) 2016/679", riferimento="Art. 9, par. 2, lett. a, c, h, i, j"),
dict(id="GDPR-08", tema="gdpr", domanda="Entro quanto tempo va notificata una violazione dei dati personali all'autorità di controllo?",
 risposta="Senza ingiustificato ritardo e, ove possibile, entro 72 ore dal momento in cui il titolare ne è venuto a conoscenza. Se la notifica supera le 72 ore deve essere corredata dei motivi del ritardo. Non è dovuta se è improbabile che la violazione presenti un rischio per i diritti e le libertà.",
 fonte="Regolamento (UE) 2016/679", riferimento="Art. 33, par. 1"),
dict(id="GDPR-09", tema="gdpr", domanda="Quando va comunicata la violazione anche agli interessati?",
 risposta="Quando è probabile che la violazione presenti un rischio ELEVATO per i diritti e le libertà delle persone fisiche; la comunicazione va fatta senza ingiustificato ritardo e con linguaggio semplice e chiaro.",
 fonte="Regolamento (UE) 2016/679", riferimento="Art. 34, par. 1 e 2"),
dict(id="GDPR-10", tema="gdpr", domanda="In quali tre casi la valutazione d'impatto (DPIA) è obbligatoria secondo l'art. 35, par. 3?",
 risposta="Valutazione sistematica e globale di aspetti personali basata su trattamento automatizzato, compresa la profilazione, con effetti giuridici o analogamente significativi; trattamento su larga scala di categorie particolari di dati o di dati relativi a condanne e reati; sorveglianza sistematica su larga scala di zone accessibili al pubblico.",
 fonte="Regolamento (UE) 2016/679", riferimento="Art. 35, par. 3, lett. a-c"),
dict(id="GDPR-11", tema="gdpr", domanda="Che cosa impone il principio di protezione dei dati fin dalla progettazione e per impostazione predefinita?",
 risposta="Il titolare deve attuare misure tecniche e organizzative adeguate — come la pseudonimizzazione — sia al momento di determinare i mezzi del trattamento sia durante il trattamento stesso, e garantire per impostazione predefinita che siano trattati solo i dati necessari per ciascuna finalità.",
 fonte="Regolamento (UE) 2016/679", riferimento="Art. 25, par. 1 e 2"),
dict(id="GDPR-12", tema="gdpr", domanda="Che cos'è il registro delle attività di trattamento e chi deve tenerlo?",
 risposta="Un registro scritto, anche elettronico, delle attività di trattamento sotto la responsabilità del titolare. Obbligatorio per organizzazioni con almeno 250 dipendenti e, a prescindere dalla dimensione, quando il trattamento può presentare un rischio per i diritti, non è occasionale o riguarda categorie particolari di dati.",
 fonte="Regolamento (UE) 2016/679", riferimento="Art. 30, par. 1 e 5"),
dict(id="GDPR-13", tema="gdpr", domanda="Quali misure di sicurezza cita espressamente l'art. 32?",
 risposta="Pseudonimizzazione e cifratura; capacità di assicurare riservatezza, integrità, disponibilità e resilienza dei sistemi; capacità di ripristinare tempestivamente disponibilità e accesso in caso di incidente; procedura per testare e valutare regolarmente l'efficacia delle misure.",
 fonte="Regolamento (UE) 2016/679", riferimento="Art. 32, par. 1, lett. a-d"),
dict(id="GDPR-14", tema="gdpr", domanda="Quando è obbligatoria la designazione di un responsabile della protezione dei dati (DPO)?",
 risposta="Quando il trattamento è effettuato da un'autorità o organismo pubblico; quando le attività principali consistono in trattamenti che richiedono monitoraggio regolare e sistematico su larga scala; quando consistono nel trattamento su larga scala di categorie particolari di dati o di dati giudiziari.",
 fonte="Regolamento (UE) 2016/679", riferimento="Art. 37, par. 1, lett. a-c"),
dict(id="GDPR-15", tema="gdpr", domanda="Quali sono i due livelli di sanzione amministrativa previsti dal GDPR?",
 risposta="Fino a 10 milioni di euro o al 2% del fatturato mondiale annuo per violazioni di obblighi come registro, sicurezza e DPIA; fino a 20 milioni o al 4% per violazioni dei principi, delle basi giuridiche, dei diritti degli interessati e delle regole sui trasferimenti. Si applica l'importo maggiore tra i due.",
 fonte="Regolamento (UE) 2016/679", riferimento="Art. 83, par. 4 e 5"),
dict(id="GDPR-16", tema="gdpr", domanda="Quali diritti spettano all'interessato secondo il Capo III?",
 risposta="Accesso, rettifica, cancellazione, limitazione del trattamento, notifica ai destinatari, portabilità, opposizione e diritto di non essere sottoposto a decisioni basate unicamente su trattamento automatizzato.",
 fonte="Regolamento (UE) 2016/679", riferimento="Artt. 15-22"),
dict(id="GDPR-17", tema="gdpr", domanda="Entro quale termine il titolare deve rispondere a una richiesta di esercizio dei diritti?",
 risposta="Senza ingiustificato ritardo e comunque entro un mese dal ricevimento, prorogabile di ulteriori due mesi in caso di complessità o numero elevato di richieste, informando l'interessato entro il primo mese.",
 fonte="Regolamento (UE) 2016/679", riferimento="Art. 12, par. 3"),
dict(id="GDPR-18", tema="gdpr", domanda="Che cosa stabilisce l'art. 22 sulle decisioni automatizzate?",
 risposta="L'interessato ha il diritto di non essere sottoposto a una decisione basata unicamente su trattamento automatizzato, compresa la profilazione, che produca effetti giuridici o incida in modo analogamente significativo. Eccezioni: necessità contrattuale, autorizzazione normativa, consenso esplicito — con garanzie tra cui l'intervento umano.",
 fonte="Regolamento (UE) 2016/679", riferimento="Art. 22, par. 1-3"),
dict(id="GDPR-19", tema="gdpr", domanda="Su quale base si può trasferire un dato personale fuori dallo Spazio economico europeo?",
 risposta="Decisione di adeguatezza della Commissione; in mancanza, garanzie adeguate quali clausole contrattuali tipo, norme vincolanti d'impresa o codici di condotta; in via residuale, le deroghe per situazioni specifiche.",
 fonte="Regolamento (UE) 2016/679", riferimento="Artt. 45, 46 e 49"),
dict(id="GDPR-20", tema="gdpr", domanda="Qual è la differenza tra titolare e responsabile del trattamento?",
 risposta="Il titolare determina finalità e mezzi del trattamento; il responsabile tratta i dati per conto del titolare. Il rapporto va disciplinato da un contratto che ne fissa oggetto, durata, natura, finalità, tipo di dati e obblighi.",
 fonte="Regolamento (UE) 2016/679", riferimento="Art. 4 punti 7 e 8; Art. 28, par. 3"),
dict(id="GDPR-21", tema="gdpr", domanda="Quali condizioni rendono valido il consenso?",
 risposta="Deve essere libero, specifico, informato e inequivocabile, manifestato con dichiarazione o azione positiva inequivocabile; il titolare deve poterlo dimostrare e l'interessato deve poterlo revocare con la stessa facilità con cui è stato prestato.",
 fonte="Regolamento (UE) 2016/679", riferimento="Art. 4 punto 11; Art. 7"),
dict(id="GDPR-22", tema="gdpr", domanda="In che senso il consenso è una base giuridica fragile in contesto umanitario?",
 risposta="Perché deve essere libero: in una situazione di dipendenza dall'assistenza, il rifiuto può essere percepito come pregiudizievole per l'accesso ai servizi, e lo squilibrio di potere compromette la libertà della scelta. Le organizzazioni umanitarie ricorrono più spesso a interesse vitale, interesse pubblico o compiti istituzionali.",
 fonte="ICRC, Handbook on Data Protection in Humanitarian Action", riferimento="Cap. 3 — Legal bases for personal data processing"),
dict(id="GDPR-23", tema="gdpr", domanda="Che cos'è il principio di «do no harm» applicato ai dati umanitari?",
 risposta="L'obbligo di valutare se la raccolta, la conservazione o la condivisione di un dato possa esporre le persone assistite a rischi di danno — targeting, stigmatizzazione, persecuzione — e di astenersi dal trattamento quando il rischio supera il beneficio operativo.",
 fonte="OCHA Centre for Humanitarian Data, Data Responsibility Guidelines", riferimento="Principio: Do No Harm"),
dict(id="GDPR-24", tema="gdpr", domanda="Che differenza c'è tra dato personale, dato sensibile e dato demograficamente identificabile in ambito umanitario?",
 risposta="Il dato personale identifica un individuo; la categoria particolare (sensibile) riguarda salute, origine etnica, opinioni, orientamento sessuale e simili; il dato demograficamente identificabile è un dato aggregato che, per granularità geografica o di gruppo, permette comunque di identificare una comunità e può metterla a rischio.",
 fonte="OCHA Centre for Humanitarian Data", riferimento="Guidance Note on Statistical Disclosure Control"),
dict(id="GDPR-25", tema="gdpr", domanda="Qual è l'autorità di controllo italiana e come si chiama la normativa nazionale di raccordo?",
 risposta="Il Garante per la protezione dei dati personali; la normativa nazionale di adeguamento è il d.lgs. 196/2003 come modificato dal d.lgs. 101/2018, noto come Codice in materia di protezione dei dati personali.",
 fonte="d.lgs. 101/2018", riferimento="Adeguamento al Regolamento (UE) 2016/679"),

# ================================================================= AI ACT
dict(id="AIA-01", tema="ai_act", domanda="Su quale logica è costruito l'AI Act europeo?",
 risposta="Su un approccio basato sul rischio, con quattro livelli: rischio inaccettabile (pratiche vietate), alto rischio (obblighi stringenti), rischio di trasparenza (obblighi informativi) e rischio minimo (nessun obbligo specifico).",
 fonte="Regolamento (UE) 2024/1689", riferimento="Struttura generale; Considerando 26"),
dict(id="AIA-02", tema="ai_act", domanda="Cita almeno quattro pratiche di IA vietate dall'art. 5.",
 risposta="Tecniche subliminali o manipolative che distorcono il comportamento causando danno; sfruttamento di vulnerabilità legate a età, disabilità o situazione sociale; punteggio sociale da parte di autorità pubbliche o private; raccolta non mirata di immagini facciali da internet o telecamere per costruire banche dati di riconoscimento; riconoscimento delle emozioni sul lavoro e nell'istruzione; identificazione biometrica remota in tempo reale in spazi pubblici a fini di contrasto, salvo eccezioni tassative.",
 fonte="Regolamento (UE) 2024/1689", riferimento="Art. 5"),
dict(id="AIA-03", tema="ai_act", domanda="Quali settori dell'Allegato III sono più rilevanti per un'organizzazione umanitaria?",
 risposta="Occupazione e gestione dei lavoratori (selezione del personale); accesso a servizi essenziali pubblici e privati, inclusa la valutazione dell'ammissibilità alle prestazioni e la classificazione delle chiamate di emergenza; migrazione, asilo e controllo delle frontiere, inclusa la valutazione dei rischi e l'esame delle domande di asilo.",
 fonte="Regolamento (UE) 2024/1689", riferimento="Allegato III, punti 4, 5 e 7"),
dict(id="AIA-04", tema="ai_act", domanda="Quali obblighi principali gravano su un sistema di IA ad alto rischio?",
 risposta="Sistema di gestione del rischio; governance dei dati di addestramento; documentazione tecnica; registrazione automatica degli eventi (log); trasparenza e istruzioni per l'uso; sorveglianza umana effettiva; livelli adeguati di accuratezza, robustezza e cibersicurezza.",
 fonte="Regolamento (UE) 2024/1689", riferimento="Artt. 9-15"),
dict(id="AIA-05", tema="ai_act", domanda="Che cosa richiede l'art. 14 in materia di sorveglianza umana?",
 risposta="Che il sistema sia progettato in modo da poter essere effettivamente supervisionato da persone fisiche, le quali devono poter comprenderne capacità e limiti, riconoscere il rischio di automation bias, interpretare correttamente l'output e decidere di non usarlo o di interromperne il funzionamento.",
 fonte="Regolamento (UE) 2024/1689", riferimento="Art. 14"),
dict(id="AIA-06", tema="ai_act", domanda="Che cos'è un modello GPAI con rischio sistemico e qual è la soglia presuntiva?",
 risposta="Un modello per finalità generali con capacità di impatto elevato; si presume tale quando la potenza di calcolo cumulativa impiegata per l'addestramento supera 10^25 operazioni in virgola mobile.",
 fonte="Regolamento (UE) 2024/1689", riferimento="Art. 51, par. 2"),
dict(id="AIA-07", tema="ai_act", domanda="Quali obblighi di trasparenza prevede l'art. 50?",
 risposta="Informare le persone quando interagiscono con un sistema di IA; marcare in formato leggibile da macchina i contenuti sintetici generati; dichiarare l'uso di sistemi di riconoscimento delle emozioni o categorizzazione biometrica; segnalare i deep fake e i testi pubblicati su questioni di interesse pubblico generati o manipolati da IA.",
 fonte="Regolamento (UE) 2024/1689", riferimento="Art. 50"),
dict(id="AIA-08", tema="ai_act", domanda="Che differenza c'è tra fornitore e deployer ai sensi dell'AI Act?",
 risposta="Il fornitore sviluppa o fa sviluppare un sistema di IA e lo immette sul mercato con il proprio nome; il deployer lo utilizza sotto la propria autorità nell'ambito di un'attività professionale. Un'organizzazione che integra e personalizza sostanzialmente un sistema può assumere il ruolo di fornitore.",
 fonte="Regolamento (UE) 2024/1689", riferimento="Art. 3 punti 3 e 4; Art. 25"),
dict(id="AIA-09", tema="ai_act", domanda="Che cos'è la valutazione d'impatto sui diritti fondamentali e chi deve svolgerla?",
 risposta="Una valutazione che i deployer che siano organismi di diritto pubblico, o soggetti privati che forniscono servizi pubblici, devono condurre prima di usare determinati sistemi ad alto rischio, descrivendo processi, categorie di persone interessate, rischi specifici di danno e misure di sorveglianza umana.",
 fonte="Regolamento (UE) 2024/1689", riferimento="Art. 27"),
dict(id="AIA-10", tema="ai_act", domanda="Come si articola nel tempo l'applicazione dell'AI Act?",
 risposta="Entrato in vigore il 1° agosto 2024, con applicazione scaglionata: prima i divieti e l'alfabetizzazione in materia di IA, poi gli obblighi sui modelli per finalità generali, poi i sistemi ad alto rischio dell'Allegato III e infine quelli integrati in prodotti regolamentati. ATTENZIONE: il calendario è stato oggetto di proposte di modifica; verifica sempre lo stato aggiornato prima di citarlo in un documento ufficiale.",
 fonte="Regolamento (UE) 2024/1689", riferimento="Art. 113 — da verificare per eventuali modifiche successive"),
dict(id="AIA-11", tema="ai_act", domanda="Qual è la norma ISO di riferimento per un sistema di gestione dell'intelligenza artificiale?",
 risposta="La ISO/IEC 42001, che definisce requisiti per stabilire, attuare, mantenere e migliorare un sistema di gestione dell'IA, con logica Plan-Do-Check-Act analoga alla ISO/IEC 27001.",
 fonte="ISO/IEC 42001", riferimento="Artificial intelligence — Management system"),
dict(id="AIA-12", tema="ai_act", domanda="Quali sono le quattro funzioni del NIST AI Risk Management Framework?",
 risposta="Govern (cultura e responsabilità), Map (contestualizzare e identificare i rischi), Measure (analizzare e monitorare), Manage (dare priorità e agire sui rischi). Govern è trasversale alle altre tre.",
 fonte="NIST AI RMF 1.0", riferimento="Core functions"),

# ================================================================= MODELLAZIONE
dict(id="MOD-01", tema="modellazione", domanda="Che cos'è la «grana» (grain) di una tabella dei fatti e perché si dichiara per prima?",
 risposta="È la definizione esatta di che cosa rappresenta una singola riga della tabella dei fatti. Si dichiara prima di scegliere dimensioni e misure perché ogni decisione successiva dipende da essa; una grana ambigua produce doppi conteggi.",
 fonte="Kimball & Ross, The Data Warehouse Toolkit, 3ª ed.", riferimento="Cap. 1 — Four-step dimensional design process"),
dict(id="MOD-02", tema="modellazione", domanda="Quali sono i quattro passi del processo di progettazione dimensionale?",
 risposta="Selezionare il processo aziendale; dichiarare la grana; identificare le dimensioni; identificare i fatti.",
 fonte="Kimball & Ross, The Data Warehouse Toolkit, 3ª ed.", riferimento="Cap. 1"),
dict(id="MOD-03", tema="modellazione", domanda="Quali sono i tre tipi fondamentali di tabella dei fatti?",
 risposta="Transazionale (una riga per evento), snapshot periodico (una riga per periodo e entità), snapshot cumulativo (una riga per processo con più tappe, aggiornata nel tempo).",
 fonte="Kimball & Ross, The Data Warehouse Toolkit, 3ª ed.", riferimento="Cap. 1 — Fact table types"),
dict(id="MOD-04", tema="modellazione", domanda="Che cos'è una tabella dei fatti «factless» e a cosa serve?",
 risposta="Una tabella dei fatti senza misure numeriche, che registra il verificarsi di un evento o una condizione di copertura. Serve a contare eventi e, soprattutto, a rispondere a domande su ciò che NON è accaduto.",
 fonte="Kimball & Ross, The Data Warehouse Toolkit, 3ª ed.", riferimento="Cap. 3 — Factless fact tables"),
dict(id="MOD-05", tema="modellazione", domanda="Che differenza c'è tra misura additiva, semi-additiva e non additiva?",
 risposta="L'additiva si può sommare su tutte le dimensioni; la semi-additiva si può sommare su alcune ma non sul tempo (per esempio un saldo o una giacenza); la non additiva non si può sommare affatto (per esempio una percentuale o un rapporto), e va ricalcolata dai suoi componenti.",
 fonte="Kimball & Ross, The Data Warehouse Toolkit, 3ª ed.", riferimento="Cap. 1 — Additivity"),
dict(id="MOD-06", tema="modellazione", domanda="Che cos'è una dimensione conforme e perché è il cardine dell'architettura a bus?",
 risposta="Una dimensione condivisa e identica tra più tabelle dei fatti e più processi. Permette di confrontare e integrare (drill across) misure provenienti da processi diversi; senza conformità ogni data mart resta un silo.",
 fonte="Kimball & Ross, The Data Warehouse Toolkit, 3ª ed.", riferimento="Cap. 4 — Conformed dimensions, enterprise bus matrix"),
dict(id="MOD-07", tema="modellazione", domanda="Che cos'è una dimensione degenerata?",
 risposta="Un attributo dimensionale, tipicamente un identificativo di transazione come il numero d'ordine o l'ID della visita, che resta nella tabella dei fatti senza una tabella dimensionale associata perché non ha altri attributi.",
 fonte="Kimball & Ross, The Data Warehouse Toolkit, 3ª ed.", riferimento="Cap. 3 — Degenerate dimensions"),
dict(id="MOD-08", tema="modellazione", domanda="Che cos'è una junk dimension?",
 risposta="Una dimensione che raggruppa flag e indicatori a bassa cardinalità, altrimenti sparsi nella tabella dei fatti, in un'unica tabella con le combinazioni effettivamente osservate.",
 fonte="Kimball & Ross, The Data Warehouse Toolkit, 3ª ed.", riferimento="Cap. 6 — Junk dimensions"),
dict(id="MOD-09", tema="modellazione", domanda="Che cos'è una dimensione con ruoli multipli (role-playing)?",
 risposta="Una singola dimensione fisica referenziata più volte dalla stessa tabella dei fatti con significati diversi — per esempio la dimensione data usata come data di ammissione, di dimissione e di follow-up — esposta tramite viste distinte con nomi di colonna propri.",
 fonte="Kimball & Ross, The Data Warehouse Toolkit, 3ª ed.", riferimento="Cap. 6 — Role-playing dimensions"),
dict(id="MOD-10", tema="modellazione", domanda="Che cosa fa una SCD di Tipo 1?",
 risposta="Sovrascrive il valore precedente. Non conserva storia: le analisi storiche vengono riscritte come se il nuovo valore fosse sempre stato vero.",
 fonte="Kimball & Ross, The Data Warehouse Toolkit, 3ª ed.", riferimento="Cap. 5 — SCD Type 1"),
dict(id="MOD-11", tema="modellazione", domanda="Che cosa fa una SCD di Tipo 2 e quali colonne di servizio richiede?",
 risposta="Aggiunge una nuova riga con una nuova chiave surrogata a ogni cambiamento, conservando la storia. Richiede tipicamente data di inizio validità, data di fine validità e un indicatore di record corrente.",
 fonte="Kimball & Ross, The Data Warehouse Toolkit, 3ª ed.", riferimento="Cap. 5 — SCD Type 2"),
dict(id="MOD-12", tema="modellazione", domanda="Che cosa fa una SCD di Tipo 3 e quando si usa?",
 risposta="Aggiunge una colonna con il valore precedente accanto a quello corrente. Si usa per cambiamenti rari e prevedibili — per esempio una riorganizzazione territoriale — in cui serve poter analizzare i dati sia secondo la vecchia sia secondo la nuova struttura.",
 fonte="Kimball & Ross, The Data Warehouse Toolkit, 3ª ed.", riferimento="Cap. 5 — SCD Type 3"),
dict(id="MOD-13", tema="modellazione", domanda="Perché si usano chiavi surrogate invece delle chiavi naturali del sistema sorgente?",
 risposta="Per isolare il warehouse dai cambiamenti e dai riusi delle chiavi sorgente, per gestire la storia con SCD di Tipo 2, per integrare più sistemi sorgente, per gestire i membri sconosciuti o non applicabili e per ridurre lo spazio degli indici.",
 fonte="Kimball & Ross, The Data Warehouse Toolkit, 3ª ed.", riferimento="Cap. 3 — Surrogate keys"),
dict(id="MOD-14", tema="modellazione", domanda="Che differenza c'è tra schema a stella e snowflake, e perché Kimball preferisce la stella?",
 risposta="Nella stella le dimensioni sono denormalizzate in un'unica tabella; nello snowflake sono normalizzate su più livelli. Kimball preferisce la stella per semplicità di comprensione, minor numero di join e prestazioni migliori, a fronte di una ridondanza di spazio trascurabile.",
 fonte="Kimball & Ross, The Data Warehouse Toolkit, 3ª ed.", riferimento="Cap. 1 e Cap. 20"),
dict(id="MOD-15", tema="modellazione", domanda="Che cos'è una bridge table e quale problema risolve?",
 risposta="Risolve le relazioni molti-a-molti tra fatto e dimensione — per esempio più diagnosi per una singola visita — introducendo una tabella ponte con un gruppo e, se necessario, un fattore di ponderazione per evitare il doppio conteggio.",
 fonte="Kimball & Ross, The Data Warehouse Toolkit, 3ª ed.", riferimento="Cap. 14 — Multivalued dimensions and bridge tables"),
dict(id="MOD-16", tema="modellazione", domanda="Che cos'è la enterprise bus matrix?",
 risposta="Una matrice che incrocia i processi aziendali (righe) con le dimensioni conformi (colonne), usata come strumento di pianificazione per definire l'architettura del warehouse e l'ordine di costruzione incrementale.",
 fonte="Kimball & Ross, The Data Warehouse Toolkit, 3ª ed.", riferimento="Cap. 4 — Enterprise data warehouse bus matrix"),
dict(id="MOD-17", tema="modellazione", domanda="Perché una dimensione data si costruisce come tabella fisica anziché usare funzioni di data?",
 risposta="Perché consente di memorizzare attributi non derivabili per calcolo — festività, stagioni epidemiche, anni fiscali, settimane di reporting del donatore — e di avere etichette coerenti e ordinabili in tutti gli strumenti di analisi.",
 fonte="Kimball & Ross, The Data Warehouse Toolkit, 3ª ed.", riferimento="Cap. 3 — Date dimension"),
dict(id="MOD-18", tema="modellazione", domanda="Che cos'è una mini-dimension e quando si usa?",
 risposta="Una dimensione separata che accoglie gli attributi a variazione rapida di una dimensione molto grande, evitando l'esplosione di righe che si avrebbe applicando una SCD di Tipo 2 all'intera dimensione.",
 fonte="Kimball & Ross, The Data Warehouse Toolkit, 3ª ed.", riferimento="Cap. 5 — Rapidly changing monster dimensions"),
dict(id="MOD-19", tema="modellazione", domanda="Che cos'è un data contract e a che cosa serve in un'architettura moderna?",
 risposta="Un accordo esplicito e versionato tra produttore e consumatore di dati, che fissa schema, semantica, qualità attesa, frequenza di aggiornamento e proprietà. Sposta la qualità a monte, trasformando rotture silenziose in violazioni rilevabili.",
 fonte="Reis & Housley, Fundamentals of Data Engineering", riferimento="Cap. 5 — Data generation and contracts"),
dict(id="MOD-20", tema="modellazione", domanda="Qual è la differenza tra ETL ed ELT e che cosa ha spostato l'equilibrio?",
 risposta="Nell'ETL la trasformazione avviene prima del caricamento, su un motore esterno; nell'ELT i dati grezzi vengono caricati e trasformati dentro il warehouse. L'equilibrio si è spostato verso ELT con la disponibilità di motori colonnari scalabili a basso costo di calcolo.",
 fonte="Reis & Housley, Fundamentals of Data Engineering", riferimento="Cap. 8 — Queries, modeling and transformation"),
dict(id="MOD-21", tema="modellazione", domanda="Che cosa sono idempotenza e carico incrementale in una pipeline?",
 risposta="Idempotenza è la proprietà per cui rieseguire la stessa operazione produce lo stesso stato finale, senza duplicare. Il carico incrementale processa solo i dati nuovi o modificati dall'ultima esecuzione; insieme rendono la pipeline sicura da rieseguire dopo un guasto.",
 fonte="Reis & Housley, Fundamentals of Data Engineering", riferimento="Cap. 5 e Cap. 8"),
dict(id="MOD-22", tema="modellazione", domanda="Che cosa distingue un data lake, un data warehouse e un lakehouse?",
 risposta="Il lake conserva dati grezzi in formati aperti su storage a oggetti, con schema applicato in lettura; il warehouse conserva dati strutturati e modellati con schema applicato in scrittura; il lakehouse aggiunge allo storage aperto un livello transazionale con tabelle, versionamento e garanzie ACID.",
 fonte="Reis & Housley, Fundamentals of Data Engineering", riferimento="Cap. 3 — Data architecture"),
dict(id="MOD-23", tema="modellazione", domanda="Quali sono le sei dimensioni classiche della qualità dei dati?",
 risposta="Completezza, accuratezza, coerenza, tempestività, validità e unicità.",
 fonte="DAMA, DMBOK 2", riferimento="Cap. 13 — Data Quality"),
dict(id="MOD-24", tema="modellazione", domanda="Che cos'è la data stewardship e in cosa differisce dalla data ownership?",
 risposta="La stewardship è la responsabilità operativa di curare definizioni, qualità e uso corretto di un dominio di dati; la ownership è la responsabilità decisionale e di accountability sul dato. Lo steward esegue e presidia, l'owner decide e risponde.",
 fonte="DAMA, DMBOK 2", riferimento="Cap. 3 — Data Governance"),
dict(id="MOD-25", tema="modellazione", domanda="Che cos'è il lineage dei dati e a che cosa serve concretamente?",
 risposta="La tracciabilità del percorso di un dato dalla sorgente al consumo, con le trasformazioni applicate. Serve per analisi d'impatto prima di una modifica, per diagnosi delle cause a valle di un errore e per dimostrare conformità in sede di audit.",
 fonte="DAMA, DMBOK 2", riferimento="Cap. 12 — Metadata Management"),
]
